package org.hibernateDomain;
// Generated Dec 14, 2011 1:16:26 PM by Hibernate Tools 3.2.0.CR1


import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Long id;
     private Date date;
     private String title;

    public Event() {
    }

    public Event(Date date, String title) {
       this.date = date;
       this.title = title;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


